---
title: "Presentation"
output:
  pdf_document:
    extra_dependencies:
      babel : ["english", "russian"]
    keep_tex: true
    latex_engine: xelatex
---

```{r include=FALSE}
library(kableExtra)
library(kmlShape)
library(rmutil)
library(MASS)
```

Quadrant count ratio (QCR):
```{r}
qcr <- function(X, Y) {
  r_Q <- 0
  med_x <- median(X)
  med_y <- median(Y)
  for (i in 1:length(X)) {
   r_Q <- r_Q + sign(X[[i]] - med_x) * sign(Y[[i]] - med_y)
  }
  r_Q <- r_Q / length(X)
}
```



```{r}
rho <- 0.5
K <- matrix(c(1,rho,rho,1), nrow = 2, ncol = 2)
mu <- c(X = 0, Y = 0)
dta = mvrnorm(n = 1000, mu = mu, Sigma = K)
plot(dta)
```

```{r}
rho <- c(0, 0.5, 0.9)
sample_size <- c(20, 60, 100)
number_of_tests <- 1000
for (size in sample_size) {
  pearson_res <- list()
  spearman_res <- list()
  rcq_res <- list()
  for (i in 1:number_of_tests) {
    
  }
}
#for 
```

```{r}
number_of_tests <- 1000
probs <- c(0.9,0.1)
#sample_size <- c(20, 60, 100)
sample_size <- c(100)
for (size in sample_size) {
  pearson_res_mixt = list()
  spearman_res_mixt = list()
  qcr_res_mixt = list()
  K1 <- matrix(c(1,0.9,0.9,1), nrow = 2, ncol = 2)
  mu <- c(X = 0, Y = 0)
  K2 <- matrix(c(100,-90,-90,100), nrow = 2, ncol = 2)
  for (i in 1:number_of_tests) {
    n1 <- rbinom(1, size = size, prob = probs[1])
    n2 <- size - n1
    dta1 <- if (n1 == 0) NULL else mvrnorm(n = n1, mu = mu, Sigma = K1)
    dta2 <- if (n2 == 0) NULL else mvrnorm(n = n2, mu = mu, Sigma = K2)
    dta <- rbind(dta1, dta2)
    pearson_res_mixt[i] <- cor(dta[1:size], dta[(size + 1):(2 * size)], 
                               method = "pearson")
    spearman_res_mixt[i] <- cor(dta[1:size], dta[(size + 1):(2 * size)],
                                method = "spearman")
    qcr_res_mixt[i] <- qcr(dta[1:size], dta[(size + 1):(2 * size)])
  }
  pearson_res_mixt = unlist(pearson_res_mixt)
  spearman_res_mixt = unlist(spearman_res_mixt)
  qcr_res_mixt = unlist(qcr_res_mixt)
  Ez = c(mean(pearson_res_mixt), mean(spearman_res_mixt), mean(qcr_res_mixt))
  Dz = c(var(pearson_res_mixt), var(spearman_res_mixt), var(qcr_res_mixt))
  Ez2 = Dz + Ez ^ 2
}
```


